BEGIN TRANSACTION;

ALTER TABLE Users
ADD RegisteredAtUtc DATETIME2 NOT NULL
CONSTRAINT DF_Users_RegisteredAtUtc DEFAULT (SYSUTCDATETIME());

ALTER TABLE Users
ADD HasActiveRequestLimit BIT NOT NULL
CONSTRAINT DF_Users_HasActiveRequestLimit DEFAULT (1);

COMMIT;